### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/digital-image-processing-lab#1]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by pranav6670** [comment]
For what do you need the Readme? The code explanation?

**Comment by Rishabh04-02** [comment]
Well, that would take too long.
I just want it in the below format:

* **[Name of Program]()(and link to the program)** - Brief description (<3 lines).

e.g. 
* **[Contrast Stretching](https://github.com/Rishabh04-02/digital-image-processing-lab/blob/master/Contrast-stretching)** - Contrast stretching is a simple image enhancement technique that improves the contrast in an image by expanding the dynamic range of intensity values it contains.

**Comment by rjrahul10** [comment]
let me dot it for you @pranav6670

**Comment by Rishabh04-02** [comment]
@rjrahul10 go ahead 👍
